### ISSUE TITLE
CalledProcessError

### ISSUE THREAD

**Issue by MrFlywheel** [inwe-boku/lecture-scientific-programming#10]
Dear Peter and Johannes,

we tried to run the code as printed on the slides, but all of us got the following error-message:

![Error_HÜ2](https://user-images.githubusercontent.com/62103756/77852298-3723e880-71de-11ea-8d3b-40f99e105d37.PNG)

could you help us out?
The previous task looks like this:

![Error2_HÜ2](https://user-images.githubusercontent.com/62103756/77852343-7a7e5700-71de-11ea-8c35-6df6c45e053a.PNG)

Thank you!
Best regards 
Noah

**Comment by lumbric** [comment]
You have to change only the three lines below `# change this:`, the Git user name and mail address is read automatically from your Git repository.

How this works: The function `git_config_value(param)` will call the command `git config user.email` or `git config user.name` which prints the configured email or name and is then used in the script.  Therefore `param` needs to be set to `name` or `email` and not to your name or your e-mail.

Feel free to close the issue if your question was answered.

**Comment by MrFlywheel** [comment]
Thank you, we fixed it!
