### ISSUE TITLE
Permission Error

### ISSUE THREAD

**Issue by adob360** [inwe-boku/lecture-scientific-programming#11]
Hello Peter and Johannes,

I am trying to do the homework, but I have no permission either to create a new Notebook in the homework02-conda-python folder or to run one. If I do so it says PermissionError Permission denied: "group-member<adob360>.txt". Do you have any idea what I could do to get permission?

Regards
adob360

**Comment by adob360** [comment]
I was able to solve the problem, it worked now.

**Comment by lumbric** [comment]
If you think the solution is relevant for others too, please add it to the ticket!

**Comment by adob360** [comment]
I don´t think so, because it was an issue with OneDrive
