### ISSUE TITLE
Homework04 

### ISSUE THREAD

**Issue by barbarakalous** [inwe-boku/lecture-scientific-programming#17]
What exactly do you want to know when you ask the question at exercise 4: “To solve the exercise find out how to generate random values with Numpy! How did you find an answer? Which possible ways are there? **List at least 2 to 5 different ways to look up what a numpy function does!**” Do you want us to list ways to generate random values, or really how to look up what numpy functions do (like google)? Thanks!

**Comment by lumbric** [comment]
Oh yes, that could be a bit more clear. We wanted to ask about ways to to find information about Numpy and list them - like google, not all ways to generate random numbers.

**Comment by raphiNi** [comment]
We are not quit sure about what we should do exactly in exercise 4. It is written, that we should  calculate the mean value of the first i values for  𝑖=1,…,100  and plot this list too...as the mean of the first 100 values is just one value, a list of one value is returned..is this correct? Or did we unterstand something wrong about the calculation of the mean? Thank you so far!

**Comment by lumbric** [comment]
Sorry about the confusion with exercise 4! The description seems to be way more confusing then helping. I'll send out a clarification later today via BOKU learn. Feel free to re-open this ticket then, if this doesn't help either.

**Comment by k1025610** [comment]
> 
> 
> Sorry about the confusion with exercise 4! The description seems to be way more confusing then helping. I'll send out a clarification later today via BOKU learn. Feel free to re-open this ticket then, if this doesn't help either.

maybe it helps to provide the whole formula? somehow like
mean(i) = 1/i * sum(x(i)) for i=1...100
... maybe this makes it more clear, that there is one calulated mean value for each position i in the list x
(sorry, could not find a way to use mathematical formulas in a github issue)

**Comment by lumbric** [comment]
I thought about simply using `np.mean()`. Not sure if the formula is making things easier then.
