### ISSUE TITLE
Permission denied

### ISSUE THREAD

**Issue by aleks-cortijo** [inwe-boku/lecture-scientific-programming#20]
I ran into an error while executing the second cell of homework.

`PermissionError`

`---> 10     with open(CONFIG_FILE) as f:`

`PermissionError: [Errno 13] Permission denied: 'mypath'`

Never had the problem before that the entsoe-data can't be accessed; the path is correct, and also i'm logged in as admin. 

Thanks in advance

**Comment by lumbric** [comment]
Hm... I am afraid that the new config file thingy has a bug (on some computers).
Could you execute `os.getcwd()` and `os.path.exists(CONFIG_FILE)` (after CONFIG_FILE has been defined to be `'../entsoe-data.config'`) in homework07.ipynb?

What this cell should do: check if there is a config file in the folder above which is called `entsoe-data.config`. If it does not exist, create it (it's a simple text file) and ask the user for a path and write it to the config file. If it exists already, just read the path from there.

```
if not os.path.exists(CONFIG_FILE):
    download_dir = input('Path to ENTSO-E data folder: ')
    if not os.path.isdir(download_dir):
        raise RuntimeError(f'Invalid download_dir, please run cell again: {download_dir}')
    with open(CONFIG_FILE, 'w') as f:
        f.write(download_dir)
else:
    with open(CONFIG_FILE) as f:
        download_dir = f.read()
```

**Comment by aleks-cortijo** [comment]
Well, that did the trick! At least i don't get an error message

 Thanks very much

**Comment by lumbric** [comment]
Uh that's weird! The code was meant just to find the error, not to fix it :)
I doubt that anything I've posted above could have fixed the error. but if it's working now, let's pretend nothing happened.

**Comment by aleks-cortijo** [comment]
in this case 'have you tried restarting your computer' was the solution to my problem :grinning:

**Comment by lumbric** [comment]
:rofl: Ok, well then that's fine too! Long time ago, I overheard a conversation between a Linux sysadmin and a Windows sysadmin. The Linux sysadmin desperately tried to figure out what was wrong in the Windows machine and then finally solved the problem by following the Windows sysadmin' advice: just install all Windows updates and see if it works. Indeed installing all Windows updates solved the problems. The Windwos sysadmin then said: "siehst du, einfach einmal mit der Schrotflinte draufschießen und geht wieder" :)
