### ISSUE TITLE
Homework 1: Change file?

### ISSUE THREAD

**Issue by ghost** [inwe-boku/lecture-scientific-programming#4]
Dear all
what is meant with the instruction that we should "change a file"? Where should we change a file and how? 
Anyone ideas?

**Comment by lumbric** [comment]
I've tried to clarify the instructions in the PDF (just updated). You can edit any file in the GIT repository and do any arbitrary change. This just a test. For example edit the `README.md` and add "I was here".

(Feel free to close the issue if your question was answered.)
